config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'doses/new'
  # get 'doses/create'
  # get 'doses/destroy'
  # get 'cocktails/index'
  # get 'cocktails/show'
  # get 'cocktails/new'
  # get 'cocktails/create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails do
    resources :doses, only: [:create]
  end
  resources :doses, only: [:destroy]
  delete 'cocktail/:id', to: 'cocktails#destroy', as: :delete_cocktail
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true, allow_blank: true
  validates :cocktail, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, uniqueness: true, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktails_path(@cocktail)
    else
      render :new
    end
  end

  # def update
  #   @cocktail = Cocktail.find(params[:id])
  #   @cocktail.update
  # end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  # def new
  #   @cocktail = Cocktail.find(params[:cocktail_id])
  #   raise
  # end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render "cocktails/new"
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = Cocktail.find(@dose.cocktail_id)
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/index.html.erb
<div class="background" >
  <div class="container-cocktail">
    <header class="d-flex flex-column align-items-center justify-content-center">
      <h1 class="boteco">Boteco Posh!</h1>
      <p class="boteco1">Amazing drinks for amazing people!</p>

    </header>
  <h1 class="index-title"></h1>
    <div class="container-fluid my-flexy">
      <div class="card-box-index">
        <% @cocktails.each do |cocktail| %>
          <%= link_to(cocktail_path(cocktail), class: "nav-link") do %>
            <div class="cards-index">
               <div class="card-img" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(<%= cl_image_path cocktail.photo %>)" >
                </div>
                <div class="info-cont">
                  <%= cocktail.name %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>Create your favorite cocktail! </h1>

      <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, wrapper_html: { class: "upload" } %>
        <%= f.input :photo_cache, as: :hidden, wrapper_html: { class: "upload-button" } %>
        <%= f.button :submit, class: 'btn btn-success'%>
      <% end %>
      <br>
    <%= link_to "Back to cocktail list", root_path, class: 'btn btn-outline-success back' %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
 <div class="container">
 <h1><%= @cocktail.name %></h1>
 </div>
  <div class="row">
    <div class="col-sm-12 col-md-6">
      <h3>Recipe</h3>
      <table class="table table-bordered">
        <tbody>
          <thead>
            <th>Ingredient</th>
            <th>Description</th>
            <th>Action</th>
          </thead>
          <% @cocktail.doses.each do |dose| %>
            <tr>
              <td><%= dose.ingredient.name %></td>
              <td><%= dose.description %></td>
              <td>
                <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
                  <i class="fa fa-trash destroy_dose"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
  <%= link_to "Back to all cocktails", root_path, class: 'btn btn-success' %>
  <%= link_to "Delete", delete_cocktail_path, method: :delete,
data: {confirm: "Are you sure?"}, class: 'btn btn-success' %>
    </div>
    <div class="col-sm-12 col-md-6">
      <%= render "doses/new", cocktail: @cocktail, dose: @dose %>

    </div>
  </div>

app/views/doses/_new.html.erb
<div class="container">

  <h3>Add Ingredients & Doses!</h3>
  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.association :ingredient, input_html: { class: "beautiful-dropdown" }, include_hidden: false %>
    <%= f.input :description %>
    <%= f.button :submit, class: "btn btn-success" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag %>
    <title>Cocktail is Life!</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/rminasi"><i class="fab fa-github"></i></a>
    <a href="https://www.instagram.com/raquelminasi/"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/raquelminasi"><i class="fab fa-facebook"></i></a>
    <a href="https://linkedin.com/in/raquelminasi/"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This website was made with <i class="fas fa-cocktail"></i> by Raquel Minasi
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="button">
    <%= link_to "Add a cocktail", new_cocktail_path, class: "btn btn-success btn-md radius:10px" %>
  </div>
</div>